### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SadhuRus** [Perkovec/tg-cli-node#1]
All do by instruction..

Write me this:

root@myfuns:~# node telegramServer.js

> /root/telegramServer.js:6
> Client.connect(connection => {
>                            ^
> SyntaxError: Unexpected token >
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:906:3

**Comment by Perkovec** [comment]
@SadhuRus use latest node.js version.

**Comment by SadhuRus** [comment]
YES!!! Now its work! Thank you
